/*
 * This file was autogenerated by OSQP on Fri May  3 11:50:22 2024
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef CVXQP2_S_H_
#define CVXQP2_S_H_

#include "osqp_api_types.h"

/* Only include the problem data, not the solver object */
#define ONLY_PROBLEM_DATA

#ifdef __cplusplus
extern "C" {
#endif

extern OSQPInt cvxqp2_s_data_n;
extern OSQPInt cvxqp2_s_data_m;

extern OSQPCscMatrix cvxqp2_s_data_P_csc;
extern OSQPCscMatrix cvxqp2_s_data_A_csc;

extern OSQPFloat cvxqp2_s_data_q_val[];
extern OSQPFloat cvxqp2_s_data_l_val[];
extern OSQPFloat cvxqp2_s_data_u_val[];

extern OSQPSettings cvxqp2_s_settings;

#ifndef ONLY_PROBLEM_DATA
  extern OSQPSolver cvxqp2_s_solver;
#endif

#ifdef __cplusplus
}
#endif

#endif /* ifndef CVXQP2_S_H_ */
