/*
 * This file was autogenerated by OSQP on Thu Sep 26 13:02:44 2024
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef HS21_H_
#define HS21_H_

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif
  extern OSQPInt hs21_data_n;
  extern OSQPInt hs21_data_m;

  extern OSQPCscMatrix hs21_data_P_csc;
  extern OSQPCscMatrix hs21_data_A_csc;

  extern OSQPFloat hs21_data_q_val[];
  extern OSQPFloat hs21_data_l_val[];
  extern OSQPFloat hs21_data_u_val[];

  extern OSQPSettings hs21_settings;

#ifdef __cplusplus
}
#endif

#endif /* ifndef HS21_H_ */
