/*
 * This file was autogenerated by OSQP on Thu Sep 26 13:02:42 2024
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef HS35_H_
#define HS35_H_

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif
  extern OSQPInt hs35_data_n;
  extern OSQPInt hs35_data_m;

  extern OSQPCscMatrix hs35_data_P_csc;
  extern OSQPCscMatrix hs35_data_A_csc;

  extern OSQPFloat hs35_data_q_val[];
  extern OSQPFloat hs35_data_l_val[];
  extern OSQPFloat hs35_data_u_val[];

  extern OSQPSettings hs35_settings;

#ifdef __cplusplus
}
#endif

#endif /* ifndef HS35_H_ */
