/*
 * This file was autogenerated by OSQP on Thu Sep 26 13:02:42 2024
 *
 * This file contains the workspace variables needed by OSQP.
 */

#include "hs35.h"
#include "types.h"

/* Define the settings structure */
OSQPSettings hs35_settings = {
  0,
  OSQP_DIRECT_SOLVER,
  1,
  0,
  0,
  1,
  10,
  0,
  (OSQPFloat)0.10000000000000000555,
  1,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)1.60000000000000008882,
  20,
  10,
  (OSQPFloat)0.14999999999999999445,
  1,
  2,
  0,
  (OSQPFloat)0.40000000000000002220,
  (OSQPFloat)5.00000000000000000000,
  1000000000,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)0.00000000000000100000,
  (OSQPFloat)0.00000000000000100000,
  0,
  25,
  1,
  (OSQPFloat)1000.00000000000000000000,
  (OSQPFloat)0.00000100000000000000,
  3,
};

/* Define the data structure */

OSQPInt hs35_data_n = 3;
OSQPInt hs35_data_m = 4;

OSQPInt hs35_data_P_csc_p[4] = {
  0,
  1,
  3,
  5,
};
OSQPInt hs35_data_P_csc_i[5] = {
  0,
  0,
  1,
  0,
  2,
};
OSQPFloat hs35_data_P_csc_x[5] = {
  (OSQPFloat)0.35355339059327378637,
  (OSQPFloat)0.17677669529663689318,
  (OSQPFloat)0.35355339059327378637,
  (OSQPFloat)0.17677669529663689318,
  (OSQPFloat)0.17677669529663689318,
};
OSQPCscMatrix hs35_data_P_csc = {
  3,
  3,
  hs35_data_P_csc_p,
  hs35_data_P_csc_i,
  hs35_data_P_csc_x,
  5,
  -1,
};

OSQPInt hs35_data_A_csc_p[4] = {
  0,
  2,
  4,
  6,
};
OSQPInt hs35_data_A_csc_i[6] = {
  0,
  1,
  0,
  2,
  0,
  3,
};
OSQPFloat hs35_data_A_csc_x[6] = {
  (OSQPFloat)-0.50000000000000011102,
  (OSQPFloat)1.00000000000000022204,
  (OSQPFloat)-0.50000000000000011102,
  (OSQPFloat)1.00000000000000022204,
  (OSQPFloat)-1.00000000000000022204,
  (OSQPFloat)0.99932332750265073784,
};
OSQPCscMatrix hs35_data_A_csc = {
  4,
  3,
  hs35_data_A_csc_p,
  hs35_data_A_csc_i,
  hs35_data_A_csc_x,
  6,
  -1,
};

OSQPFloat hs35_data_q_val[3] = {
  (OSQPFloat)-1.00000000000000000000,
  (OSQPFloat)-0.75000000000000000000,
  (OSQPFloat)-0.50000000000000000000,
};

OSQPFloat hs35_data_l_val[4] = {
  (OSQPFloat)-2.12132034355964282923,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};

OSQPFloat hs35_data_u_val[4] = {
  (OSQPFloat)70710678118654754816.00000000000000000000,
  (OSQPFloat)141421356237309509632.00000000000000000000,
  (OSQPFloat)141421356237309509632.00000000000000000000,
  (OSQPFloat)141325660295005880320.00000000000000000000,
};
