/*
 * This file was autogenerated by OSQP on Wed Nov  2 13:22:21 2022
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside largeqp.c.
 */

#ifndef LARGE_QP_H_
#define LARGE_QP_H_

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPFloat largeqp_obj_val;

  extern OSQPInt largeqp_data_n;
  extern OSQPInt largeqp_data_m;

  extern OSQPCscMatrix largeqp_data_P_csc;
  extern OSQPCscMatrix largeqp_data_A_csc;

  extern OSQPFloat largeqp_data_q_val[];
  extern OSQPFloat largeqp_data_l_val[];
  extern OSQPFloat largeqp_data_u_val[];

  extern OSQPSettings largeqp_settings;

#ifdef __cplusplus
}
#endif

#endif /* ifndef LARGE_QP_H_ */
