/*
 * This file was autogenerated by OSQP on Thu Oct 10 09:52:27 2024
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef PRIMALC1_H_
#define PRIMALC1_H_

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPInt primalc1_data_n;
  extern OSQPInt primalc1_data_m;

  extern OSQPCscMatrix primalc1_data_P_csc;
  extern OSQPCscMatrix primalc1_data_A_csc;

  extern OSQPFloat primalc1_data_q_val[];
  extern OSQPFloat primalc1_data_l_val[];
  extern OSQPFloat primalc1_data_u_val[];

  extern OSQPSettings primalc1_settings;

#ifdef __cplusplus
}
#endif

#endif /* ifndef PRIMALC1_H_ */
