/*
 * This file was autogenerated by OSQP on Fri May  3 12:03:51 2024
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef QPCBLEND_H_
#define QPCBLEND_H_

#include "osqp_api_types.h"

/* Only include the problem data, not the solver object */
#define ONLY_PROBLEM_DATA

#ifdef __cplusplus
extern "C" {
#endif

extern OSQPInt qpcblend_data_n;
extern OSQPInt qpcblend_data_m;

extern OSQPCscMatrix qpcblend_data_P_csc;
extern OSQPCscMatrix qpcblend_data_A_csc;

extern OSQPFloat qpcblend_data_q_val[];
extern OSQPFloat qpcblend_data_l_val[];
extern OSQPFloat qpcblend_data_u_val[];

extern OSQPSettings qpcblend_settings;

#ifndef ONLY_PROBLEM_DATA
  extern OSQPSolver solver;
#endif

#ifdef __cplusplus
}
#endif

#endif /* ifndef QPCBLEND_H_ */
