/*
 * This file was autogenerated by OSQP on Thu Sep 26 13:02:38 2024
 *
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef QPTEST_H_
#define QPTEST_H_

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif
  extern OSQPFloat qptest_obj_val;

  extern OSQPInt qptest_data_n;
  extern OSQPInt qptest_data_m;

  extern OSQPCscMatrix qptest_data_P_csc;
  extern OSQPCscMatrix qptest_data_A_csc;

  extern OSQPFloat qptest_data_q_val[];
  extern OSQPFloat qptest_data_l_val[];
  extern OSQPFloat qptest_data_u_val[];

  extern OSQPSettings qptest_settings;

#ifdef __cplusplus
}
#endif

#endif /* ifndef QPTEST_H_ */
