/*
 * This file was autogenerated by OSQP on Thu Sep 26 13:02:38 2024
 *
 * This file contains the workspace variables needed by OSQP.
 */

#include "qptest.h"
#include "types.h"

/* Define the settings structure */
OSQPSettings qptest_settings = {
  0,
  OSQP_DIRECT_SOLVER,
  1,
  0,
  0,
  1,
  10,
  0,
  (OSQPFloat)0.10000000000000000555,
  1,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)1.60000000000000008882,
  20,
  10,
  (OSQPFloat)0.14999999999999999445,
  1,
  2,
  0,
  (OSQPFloat)0.40000000000000002220,
  (OSQPFloat)5.00000000000000000000,
  1000000000,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)0.00000000000000100000,
  (OSQPFloat)0.00000000000000100000,
  0,
  25,
  1,
  (OSQPFloat)1000.00000000000000000000,
  (OSQPFloat)0.00000100000000000000,
  3,
};

/* Define the data structure */
OSQPInt qptest_data_n = 2;
OSQPInt qptest_data_m = 4;


OSQPInt qptest_data_P_csc_p[3] = {
  0,
  1,
  3,
};
OSQPInt qptest_data_P_csc_i[3] = {
  0,
  0,
  1,
};
OSQPFloat qptest_data_P_csc_x[3] = {
  (OSQPFloat)1.00000000000000000000,
  (OSQPFloat)0.22360679774997901936,
  (OSQPFloat)1.00000000000000022204,
};
OSQPCscMatrix qptest_data_P_csc = {
  2,
  2,
  qptest_data_P_csc_p,
  qptest_data_P_csc_i,
  qptest_data_P_csc_x,
  3,
  -1,
};

OSQPInt qptest_data_A_csc_p[3] = {
  0,
  3,
  6,
};
OSQPInt qptest_data_A_csc_i[6] = {
  0,
  1,
  2,
  0,
  1,
  3,
};
OSQPFloat qptest_data_A_csc_x[6] = {
  (OSQPFloat)0.99864711289097007896,
  (OSQPFloat)-0.55813906812935698554,
  (OSQPFloat)0.99797135585511964617,
  (OSQPFloat)0.44660856599162324088,
  (OSQPFloat)0.99842951778850297373,
  (OSQPFloat)0.99775390799327379199,
};
OSQPCscMatrix qptest_data_A_csc = {
  4,
  2,
  qptest_data_A_csc_p,
  qptest_data_A_csc_i,
  qptest_data_A_csc_x,
  6,
  -1,
};

OSQPFloat qptest_data_q_val[2] = {
  (OSQPFloat)0.53033008588991070731,
  (OSQPFloat)-0.63245553203367599338,
};
OSQPFloat qptest_data_l_val[4] = {
  (OSQPFloat)2.82460058215029086170,
  (OSQPFloat)-157865567967763529728.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPFloat qptest_data_u_val[4] = {
  (OSQPFloat)141230029107514540032.00000000000000000000,
  (OSQPFloat)9.47193407806581255670,
  (OSQPFloat)56.45378505240706346058,
  (OSQPFloat)315517489359282569216.00000000000000000000,
};
