#include <stdio.h>
#include <ctype.h>  /* -> toupper */
#include <time.h>   /* time, ctime */

#include "error.h"
#include "osqp_api_constants.h"
#include "types.h"
#include "algebra_impl.h"
#include "qdldl_interface.h"

#include "export_c_helpers.h"


static OSQPInt export_inc(OSQPSolver* solver,
                          const char* output_dir,
                          const char* file_prefix) {

  char hfname[PATH_LENGTH], incGuard[FILE_LENGTH];
  FILE *incFile;
  time_t now;
  OSQPInt i = 0;

  sprintf(hfname, "%s%s.h", output_dir, file_prefix);

  /* Open include file */
  incFile = fopen(hfname, "w");
  if (incFile == NULL)
    return osqp_error(OSQP_FOPEN_ERROR);

  /* Print comment headers containing the generation time into the files */
  time(&now);
  fprintf(incFile, "/*\n");
  fprintf(incFile, " * This file was autogenerated by OSQP on %s", ctime(&now));
  fprintf(incFile, " * \n");
  fprintf(incFile, " * This file contains the prototype for the problem data matrices\n");
  fprintf(incFile, " * used by OSQP. The actual data is contained inside %s.c.\n", file_prefix);
  fprintf(incFile, " */\n\n");

  /* Add an include-guard statement */
  sprintf(incGuard, "%s_H", file_prefix);
  while(incGuard[i]){
    incGuard[i] = toupper(incGuard[i]);
    i++;
  }
  fprintf(incFile, "#ifndef %s\n",   incGuard);
  fprintf(incFile, "#define %s\n\n", incGuard);

  /* Include required headers */
  fprintf(incFile, "#include \"osqp_api_types.h\"\n\n");

  fprintf(incFile, "#ifdef __cplusplus\n");
  fprintf(incFile, "extern \"C\" {\n");
  fprintf(incFile, "#endif\n\n");

  fprintf(incFile, "  extern OSQPCscMatrix %s_P;\n", file_prefix);
  fprintf(incFile, "  extern OSQPCscMatrix %s_P;\n", file_prefix);
  fprintf(incFile, "  extern OSQPCscMatrix %s_P;\n", file_prefix);
  fprintf(incFile, "  extern OSQPCscMatrix %s_A;\n", file_prefix);
  fprintf(incFile, "  extern OSQPFloat*    %s_q;\n", file_prefix);
  fprintf(incFile, "  extern OSQPFloat*    %s_l;\n", file_prefix);
  fprintf(incFile, "  extern OSQPFloat*    %s_u;\n", file_prefix);

  fprintf(incFile, "#ifdef __cplusplus\n");
  fprintf(incFile, "}\n");
  fprintf(incFile, "#endif\n\n");

  /* The endif for the include-guard statement */
  fprintf(incFile, "#endif /* ifndef %s */\n", incGuard);

  /* Close header file */
  fclose(incFile);

  return 0;
}


OSQPInt export_src(OSQPSolver* solver,
                    const char* output_dir,
                    const char* file_prefix) {

  OSQPInt exitflag = OSQP_NO_ERROR;
  char fname[PATH_LENGTH], cfname[PATH_LENGTH];
  FILE *srcFile;
  time_t now;

  sprintf(fname,  "%s%sworkspace", output_dir, file_prefix);
  sprintf(cfname, "%s.c",        fname);

  /* Open source file */
  srcFile = fopen(cfname, "w");
  if (srcFile == NULL)
    return osqp_error(OSQP_FOPEN_ERROR);

  /* Print comment headers containing the generation time into the files */
  time(&now);
  fprintf(srcFile, "/*\n");
  fprintf(srcFile, " * This file was autogenerated by OSQP on %s", ctime(&now));
  fprintf(srcFile, " * \n");
  fprintf(srcFile, " * This file contains the workspace variables needed by OSQP.\n");
  fprintf(srcFile, " */\n\n");

  /* Include required headers */
  fprintf(srcFile, "#include \"types.h\"\n");
  fprintf(srcFile, "#include \"algebra_impl.h\"\n");
  fprintf(srcFile, "#include \"qdldl_interface.h\"\n\n");

  fprintf(f, "/* Define the data structure */\n");
  sprintf(name, "%sdata_P", prefix);
  GENERATE_ERROR(write_OSQPMatrix(f,  data->P, name))
  sprintf(name, "%sdata_A", prefix);
  GENERATE_ERROR(write_OSQPMatrix(f,  data->A, name))
  sprintf(name, "%sdata_q", prefix);
  GENERATE_ERROR(write_OSQPVectorf(f, data->q, name))
  sprintf(name, "%sdata_l", prefix);
  GENERATE_ERROR(write_OSQPVectorf(f, data->l, name))
  sprintf(name, "%sdata_u", prefix);
  GENERATE_ERROR(write_OSQPVectorf(f, data->u, name))
  fprintf(f, "OSQPData %sdata = {\n", prefix);
  fprintf(f, "  %d,\n", data->n);
  fprintf(f, "  %d,\n", data->m);
  fprintf(f, "  &%sdata_P,\n", prefix);
  fprintf(f, "  &%sdata_A,\n", prefix);
  fprintf(f, "  &%sdata_q,\n", prefix);
  fprintf(f, "  &%sdata_l,\n", prefix);
  fprintf(f, "  &%sdata_u\n", prefix);
  fprintf(f, "};\n\n");

  /* Close header file */
  fclose(srcFile);

  return exitflag;
}

/******
* Data
*******/

static OSQPInt write_data(FILE*           f,
                          const OSQPData* data,
                          const char*     prefix) {

  OSQPInt exitflag = OSQP_NO_ERROR;
  char name[MAX_VAR_LENGTH];

  if (!data) return osqp_error(OSQP_WORKSPACE_NOT_INIT_ERROR);



  return exitflag;
}
