name: Documentation and Site Link Checker (Periodic)

on:
  schedule:
    # Run daily at 2am
    - cron: '0 2 * * *'

jobs:
  check-links-periodic:
    name: Check links (Periodic run)
    runs-on: ubuntu-latest
    steps:
      # Just running the check on the main website will also include the docs, since they
      # live at osqp.org/docs.
      - name: Check OSQP website links
        uses: filiph/linkcheck@3.0.0
        with:
          arguments: https://osqp.org -e
